# Generated by Django 2.2.5 on 2019-10-28 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191028_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date_updated'),
        ),
        migrations.AddField(
            model_name='profile',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_updated'),
            preserve_default=False,
        ),
    ]
