# Generated by Django 2.2.5 on 2019-11-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191030_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_profile_picture.png', upload_to='profile_pics'),
        ),
    ]
