# Generated by Django 2.2.5 on 2019-10-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='активный',
            field=models.BooleanField(default=True),
        ),
    ]
