# Generated by Django 2.2.5 on 2019-10-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified', '0003_auto_20191026_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='active',
            field=models.BooleanField(default=True, verbose_name='активный'),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_posted'),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_updated'),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='header',
            field=models.CharField(max_length=100, verbose_name='header'),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
    ]
