# Generated by Django 2.2.5 on 2019-10-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified', '0004_auto_20191027_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='body',
            field=models.TextField(max_length=1000, verbose_name='body'),
        ),
    ]
