# Generated by Django 2.2.5 on 2019-10-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified', '0005_auto_20191028_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classifiedad',
            options={'ordering': ('-date_updated',), 'verbose_name': 'ad', 'verbose_name_plural': 'ads'},
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='slug',
            field=models.SlugField(default='sl', max_length=100),
            preserve_default=False,
        ),
    ]
