# Generated by Django 2.2.5 on 2019-10-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified', '0006_auto_20191028_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='moderation',
            field=models.BooleanField(default=False, verbose_name='moderation'),
        ),
    ]
