# Generated by Django 2.2.5 on 2019-10-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified', '0007_classifiedad_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date_updated'),
        ),
    ]
