# Generated by Django 2.2.5 on 2019-10-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified', '0009_auto_20191030_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
