# Generated by Django 2.2.5 on 2019-10-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified', '0010_auto_20191031_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
