# Generated by Django 2.2.5 on 2019-11-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified', '0011_auto_20191031_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='image',
            field=models.ImageField(default='default_missing.png', upload_to='images'),
        ),
    ]
